server:
  port: 8084

spring:
  application:
    name: service-notification
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

fcm:
  credentials-path: classpath:firebase-credentials.json

logging:
  level:
    com.skillswap.notification: DEBUG
