server:
  port: 8083

spring:
  application:
    name: service-mission
  data:
    mongodb:
      uri: mongodb://localhost:27017/skillswap-missions
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

otp:
  expiration: 300

logging:
  level:
    com.skillswap.mission: DEBUG
