// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
  
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJqYgHQmsHIlaY1ruHT1KtUgLdJssWUI8',
    appId: '1:265511186110:web:0518f69109387d82cf38ef',
    messagingSenderId: '265511186110',
    projectId: 'skillswap-e6565',
    authDomain: 'skillswap-e6565.firebaseapp.com',
    storageBucket: 'skillswap-e6565.firebasestorage.app',
    measurementId: 'G-9FVW9GKB58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAAAXkr6u7zIADxvXb6UVZxdIWjMjD-os',
    appId: '1:265511186110:android:35614a888cb20bcecf38ef',
    messagingSenderId: '265511186110',
    projectId: 'skillswap-e6565',
    storageBucket: 'skillswap-e6565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbiLPmCcX1W8hYuqnSMWt62oqFaNstZ68',
    appId: '1:265511186110:ios:446e099f53998655cf38ef',
    messagingSenderId: '265511186110',
    projectId: 'skillswap-e6565',
    storageBucket: 'skillswap-e6565.firebasestorage.app',
    iosBundleId: 'com.example.skillswapFrontMobile',
  );

}
